# Generated by Django 3.1.1 on 2021-01-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0002_proposition_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='slug',
            field=models.SlugField(),
        ),
    ]
