# Generated by Django 3.1.1 on 2021-01-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mainslider_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslider',
            name='slider_title',
            field=models.CharField(default='Изучите наше меню', max_length=10, verbose_name='Заголовок слайда'),
        ),
    ]
