# Generated by Django 3.1.1 on 2021-01-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mainslider_slider_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='button_text',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='slider_title',
            field=models.CharField(default='Изучите наше меню', max_length=20, verbose_name='Заголовок слайда'),
        ),
    ]
