# Generated by Django 3.1.1 on 2021-01-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210131_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='need_learning_branch',
            field=models.BooleanField(default=False),
        ),
    ]
