# Generated by Django 3.1.1 on 2021-01-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_need_learning_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dont_recall',
            field=models.BooleanField(default=False),
        ),
    ]
