# Generated by Django 3.1.1 on 2021-01-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_dont_recall'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_tag_name', models.CharField(max_length=20, verbose_name='Тэг')),
                ('display_on_main', models.BooleanField(verbose_name='Отображается на главной')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_tag',
            field=models.ManyToManyField(to='core.ItemTag', verbose_name='Тэги товара'),
        ),
    ]
