# Generated by Django 3.1.1 on 2021-01-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210201_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AddField(
            model_name='itemtag',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
