# Generated by Django 3.1.1 on 2021-01-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210201_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='slider_text',
            field=models.CharField(max_length=50, verbose_name='Текст слайда'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='slider_title',
            field=models.CharField(default='Изучите наше меню', max_length=35, verbose_name='Заголовок слайда'),
        ),
    ]
