# Generated by Django 3.1.1 on 2021-02-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210201_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_eng_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Категория Eng'),
        ),
        migrations.AddField(
            model_name='category',
            name='label_eng',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='english_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtag',
            name='item_tag_eng_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тэг Eng'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='button_eng_text',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='slider_eng_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст слайда eng'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='slider_eng_title',
            field=models.CharField(blank=True, default='Изучите наше меню', max_length=35, null=True, verbose_name='Заголовок слайда eng'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pc',
            field=models.ImageField(blank=True, default='1.jpg', null=True, upload_to='photos'),
        ),
    ]
