# Generated by Django 3.1.5 on 2021-01-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210128_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionorder',
            options={'verbose_name': 'Номер заказа в сессии', 'verbose_name_plural': 'Номера заказов в сессии'},
        ),
        migrations.AddField(
            model_name='order',
            name='sessinoOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sessionorder'),
        ),
    ]
