# Generated by Django 3.1.5 on 2021-01-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210128_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='sessinoOrder',
            new_name='sessionOrder',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='sessinoOrder',
            new_name='sessionOrder',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='sessinoOrder',
            new_name='sessionOrder',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='sessinoOrder',
            new_name='sessionOrder',
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='person_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
