# Generated by Django 3.1.5 on 2021-01-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210128_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionorder',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
