# Generated by Django 3.1.5 on 2021-01-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_sessionorder_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionorder',
            name='id',
        ),
        migrations.AddField(
            model_name='sessionorder',
            name='sessionOrder_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
