# Generated by Django 3.1.5 on 2021-01-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210128_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionorder',
            old_name='sessionOrder_id',
            new_name='id',
        ),
    ]
